### ISSUE TITLE
Support multiple selections

### ISSUE THREAD

**Issue by adzenith** [hajdaini/select-until-pattern#1]
Looks like it doesn't work with multiple selections. Only the first selection is modified and all others are lost. Any chance you could add support?

Thanks!

**Comment by hajdaini** [comment]
Hello @adzenith !
 
Thank you for your feedback. I will see how to implement this feature.

**Comment by hajdaini** [comment]
Done :)

**Comment by adzenith** [comment]
Thank you!! That was fast :)
